spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/coinkeeper
  jpa:
    hibernate:
      ddl-auto: update

